[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  CONTENTFUL_ENVIRONMENT = "develop"

[context.production.environment]
  CONTENTFUL_ENVIRONMENT = "master"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[[plugins]]
  package = "@netlify/plugin-nextjs"